### ISSUE TITLE
Short-lived or long-lived access token?

### ISSUE THREAD

**Issue by bytrangle** [oorestisime/gatsby-source-dropbox#13]
When creating a new Dropbox app, users have two options for the access token: short-lived or long-lived. The long-lived access token type has been deprecated and will only be available until [mid 2021](https://www.dropbox.com/lp/developers/reference/oauth-guide).

Will this plugin still work once the long-lived token is phased out?

**Comment by ahmedghazi** [comment]
I have two apps running with db api, one can have long-lived at, my clients can't have one. I'm in a bad bad situation.

**Comment by niklas-may** [comment]
This plugin should only be used with you own dropbox account. Therefore the generated test token should be enough. Please read at [Testing with a generated token](https://developers.dropbox.com/de-de/oauth-guide#implementing-oauth)
