### ISSUE TITLE
Inline images in Markdown files are broken

### ISSUE THREAD

**Issue by bytrangle** [oorestisime/gatsby-source-dropbox#14]
Suppose we have the following Dropbox folder:
```
pandas
---- index.md
---- pandas.png
```
The `index.md` above links to the panda image with this syntax: `![](./pandas.png)`

However, when `gatsby-source-plugin` downloads those files to the `.cache` folder, the Markdown file and the panda image are in separate folders.
```
.cache
---- caches
-------- ab25ef8799d80bf6cf8342b5709807d6
------------ pandas.png
-------- facd41ebb4f9e3aa847585f8d0d95b59
------------ index.md
```
Now, when open the page created by the Markdown file, the image will be broken because it is no longer in the same folder.

Do you have any suggestion?

**Comment by niklas-may** [comment]
The [remark Dropbox image](https://github.com/niklas-may/gatsby-remark-dropbox-images) plugin should solve this problem.
