### ISSUE TITLE
How can I customized UI for the dropbox form?

### ISSUE THREAD

**Issue by tptspe** [oorestisime/gatsby-source-dropbox#28]
Hello

Thanks for your making this plugin.
I tried to install this one and build the dropbox form UI, but it doesn't work as I want.
Here is the details with my issue
https://stackoverflow.com/questions/76454031/how-to-make-the-dropbox-upload-using-gatsby-source-dropbox

Can you help me to solve my issue?
Regards
Tri

**Comment by niklas-may** [comment]
The plugin does not support file uploads.

**Comment by tptspe** [comment]
Hi niklas.
Well, Is there any plugin or idea to make the file upload form using dropbox?
What is the purpose of this plugin?

**Comment by niklas-may** [comment]
This is not an official dropbox plug-in. Please check the official dropbox website. Closing this issue.
