### ISSUE TITLE
allDropboxNode not showing in the GraphQL explorer

### ISSUE THREAD

**Issue by Vacilando** [oorestisime/gatsby-source-dropbox#5]
Installed plugin, added the config in gatsby-config.js with a valid accessToken.

Develop starts without any error, but there's no allDropboxNode in the GraphQL explorer.

Any advice on how to debug the problem?

**Comment by oorestisime** [comment]
Pretty hard to know. I suppose you have files inside right? Been some time i haven't checked this plugin so going to try to find some time soon the following days to check it up again.

**Comment by Vacilando** [comment]
It actually works fine, my bad.

What threw me off course:  if one creates a Dropbox app for one single folder then it's usually useless to specify 'path' for this plugin; Gatsby only has access to the _content_ of that folder.
Perhaps something that could be clarified in the readme.
