### ISSUE TITLE
More instructions needed

### ISSUE THREAD

**Issue by ndotmdot** [oorestisime/gatsby-source-dropbox#6]
I installed the plugin on a new site created with `gatsby new`
When i run `yarn develop` the site starts normally, but i do not see "allDropboxNode" in graphql.

I am not sure if i did set up the dropbox app correctly. these are my settings and where i generated the token

![Screen Shot 2020-04-22 at 23 41 14](https://user-images.githubusercontent.com/19529313/80036863-db096700-84f2-11ea-8e7e-ec6c906b0ceb.png)

This is my gatsby-config.js

```javascript
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-source-dropbox`,
      options: {
        accessToken: `XXXXXXXXXXXXXX`,
        extensions: ['.pdf', '.jpg', '.png', '.md'],
        path: '/website',
        recursive: true,
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```

Any further descriptions on how to set this up would be much appreciated.

**Comment by oorestisime** [comment]
Hey there, its been a while i haven't used this plugin and i unfortunately no longer a local installation.

Nevertheless i don't think dropbox changed their API so it should be working. The only possible issue in the config i see ` path: '/website',` Are you sure this is pointing to a valid path in dropbox?

**Comment by ndotmdot** [comment]
Thank you for your response. I am sure that `path: '/website'` exists. I also tried it without the path attribute. A thing that also made me curious, is that even when i use a wrong API token, i don't get any errors. Any other idea?

**Comment by oorestisime** [comment]
Maybe something changed in their API. i ll try and have a look on the weekend, unfortunately i can't right now :( sorry about this!

**Comment by ndotmdot** [comment]
Sorry, my bad, i did a stupid mistake. It all works fine now.

**Comment by oorestisime** [comment]
Nice! what was it in the end?

**Comment by ndotmdot** [comment]
Pure stupidity. I missed that when you create a dropbox App with only folder permission, that this folder needs to live within the "App" folder.

**Comment by ndotmdot** [comment]
By the way, i love your plugin and the idea of having dropbox as a simple cms. It would be great to to also create nodes from folders. To have something like "allDropboxFolder" in graphql. Then you could build pages based on folder and their content. That would be super handy for less tech savvy people and simple portfolio pages.

Even though i am new to creating gatsby-source-plugins, i would give it a try, fork yours and send a PR. I would  add it as on optional functionality with a corresponding parameter. What do you think about this?

**Comment by oorestisime** [comment]
Sounds like a great idea!  excited to see the PR!
(feel free to close a ticket since it is working :))
