### ISSUE TITLE
Can't publish PR merge to NPM

### ISSUE THREAD

**Issue by ndotmdot** [oorestisime/gatsby-source-dropbox#8]
Hi,

i just merged PR but can't publish to npm
`03 Forbidden - PUT https://registry.npmjs.org/gatsby-source-dropbox - You do not have permission to publish "gatsby-source-dropbox".`

Can you give me permission pls?
user: ndotmdot
email: hello@niklasmay.com

Thanks!

**Comment by oorestisime** [comment]
Done i think! let me know fi you run into any issues

**Comment by ndotmdot** [comment]
Great, it worktd, thanks a lot!

**Comment by oorestisime** [comment]
You rock! thanks for taking over this!
